name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Actions
      uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        pip install django
        python3 -m pip install djfernet
        pip install python-decouple
    - name: Run Tests
      run: |
        python manage.py test
